### ISSUE TITLE
Provide a LICENSE

### ISSUE THREAD

**Issue by Geod24** [deadalnix/schnorr#1]
Hey,
Wanted to make use of this code, but there is currently no license (nor dub package file).
Would it be possible for you to put a (hopefully copyleft, e.g. MIT) license on this code ?

**Comment by deadalnix** [comment]
No problem. However, please know that the version of schnorr implemented in there, while secure, is not compliant with what's becoming the de facto standard now.

**Comment by deadalnix** [comment]
Done.
